name: Deploy to AKS Cluster

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: ACR Login (using OIDC-based login session)
      uses: azure/docker-login@v1
      with:
        login-server: aksgitaction.azurecr.io

    - name: Build and Push Docker Image
      run: |
        docker build . -t aksgitaction.azurecr.io/k8sflask:${{ github.sha }}
        docker push aksgitaction.azurecr.io/k8sflask:${{ github.sha }}

    - name: Set AKS Context (OIDC-based)
      uses: Azure/aks-set-context@v1
      with:
        resource-group: AKS-GitOPS-RG
        cluster-name: AKS-GA

    - name: Create image pull secret in Kubernetes
      uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: aksgitaction.azurecr.io
        secret-name: k8s-secret

    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v4
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          aksgitaction.azurecr.io/k8sflask:${{ github.sha }}
        imagepullsecrets: |
          k8s-secret
